# Generated by Django 4.1 on 2022-08-28 14:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='answer',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='box',
            field=models.IntegerField(choices=[(1, 1), (2, 2)], default=1),
        ),
        migrations.AlterField(
            model_name='card',
            name='question',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
